# Generated by Django 3.1.7 on 2021-04-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(unique=True)),
                ('number', models.IntegerField()),
                ('semester', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(unique=True)),
                ('total_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSB.degree')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSB.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Fulfills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSB.course')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSB.requirement')),
            ],
        ),
    ]
