# Generated by Django 3.1.7 on 2021-04-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfills',
            name='depth',
            field=models.TextField(default='AI'),
        ),
    ]
