# Generated by Django 3.1.7 on 2021-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSB', '0002_fulfills_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfills',
            name='depth',
        ),
        migrations.AddField(
            model_name='fulfills',
            name='concentration',
            field=models.TextField(default='n/a'),
        ),
    ]
