# Generated by Django 3.1.7 on 2021-04-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSB', '0003_auto_20210405_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fulfills',
            options={'verbose_name_plural': 'Fulfills'},
        ),
        migrations.AlterModelOptions(
            name='requires',
            options={'verbose_name_plural': 'Requires'},
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
        ),
    ]
